name: 'GitHub Action for Mackerel API'
description: 'Call a Mackerel API endpoint and get the resulting JSON response.'
author: 'Yutaro Muta'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
