name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test_ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        npm install
    - name: lint
      run: |
        npm run lint
    - name: build
      run: |
        npm run build
    - name: test
      run: |
        npm run test
      env:
        TEST_API_KEY: ${{ secrets.MACKEREL_API_KEY }}
        TEST_ORG_NAME: ${{ secrets.MACKEREL_ORG_NAME }}
        TEST_SERVICE_NAME: ${{ secrets.MACKEREL_SERVICE_NAME }}
